name = "FlashFill"
uuid = "57d7c41d-6e6c-498a-9f71-e8603de45dca"
authors = ["Atharv Sonwane <atharvs.twm@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
